server:
  port: 8080

hotel:
  datasource:
    # Заміни 'hotel_db' на назву своєї бази даних
    url: jdbc:postgresql://localhost:5432/kursowa

#    # Користувачі, створені в security.sql
#    guest:
#      username: app_guest_user
#      password: guest123
#
#    client:
#      username: app_client_user
#      password: client123
#
#    admin:
#      username: app_admin_user
#      password: admin123
#
#    manager:
#      username: app_manager_user
#      password: manager123
#
#    owner:
#      username: app_owner_user
#      password: owner123
#
#    cleaner:
#      username: app_cleaner_user
#      password: cleaner123
#
#    accountant:
#      username: app_accountant_user
#      password: money123

spring:
  thymeleaf:
    cache: false