server:
  port: 8080

hotel:
  datasource:
    # Важливо: назви мають точно збігатися з тими, що в коді Java
    url: jdbc:postgresql://localhost:5432/kursowa?ApplicationName=HotelApp_Backend
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

    # Налаштування пулу всередині вашого префікса
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
      idle-timeout: 20000
      max-lifetime: 1800000

spring:
  thymeleaf:
    cache: false
  # Якщо ви використовуєте JPA/Hibernate, йому все одно потрібні ці дані:
  jpa:
    show-sql: true